### ISSUE TITLE
Non-core modules should have a migrate function.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#306]
@janitachalam has been doing some work on migration. They pointed out that in order to do a migration you must have a `migrate` function even if that function does nothing. We should implement the migrate function for all of our non-core modules as those will have the core module set as their admin.

https://docs.cosmwasm.com/docs/1.0/smart-contracts/migration/

**Comment by janitachalam** [comment]
Note that migration requires that a contract has an admin to perform the migration. As part of this, investigate how we may make a core module be its own admin. Since you supply the admin at instantiation,  
and if there's no admin already set then the admin can't be updated, this might require some workaround such as having another contract instantiate the contract as a temporary admin, then updating the newly created contract to be the admin of itself.

**Comment by ezekiiel** [comment]
Resolved by: https://github.com/DA0-DA0/dao-contracts/pull/314
