### ISSUE TITLE
11. Voting module design is prone to configuration risk

### ISSUE THREAD

**Issue by janitachalam** [DA0-DA0/dao-contracts#339]
[2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf](https://github.com/DA0-DA0/dao-contracts/files/8848907/2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf)

Check issue 11 of the attached audit. Evaluate the recommendation for design change.

**Comment by ezekiiel** [comment]
This is an interesting point from the audit. I think I'm inclined to stick with our current design choices because:

1. It allows the DAO to upgrade a buggy voting power modules.
2. It allows a DAO to switch voting mechanisms. Ex: DAO launches a NFT collection and would like to use those or a Multisig gets big enough that it wants to become a DAO.

We also currently benefit from this design choice in the frontend because we can write it as if there is a single core module interface we need to speak with.

It's a fair point that the core module and voting power module's are very closely related though. Merging the two contracts would require that we publish a new core module for each voting system we have.

Am open to other thoughts though. @JakeHartnell any thoughts on this?

<img width="659" alt="image" src="https://user-images.githubusercontent.com/30676292/172503087-61e0c855-555f-4520-adce-54303767d311.png">

**Comment by Callum-A** [comment]
I think this issue is more of a question for the front end and we've been working on removing as many footguns as possible on that end. I think we stick how we are and focus on a clean DAO creation and module upgrade flow via templates and wizards.
