### ISSUE TITLE
Explore invariant checks for cw721 voting contract

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#525]
if a NFT is in the set of staked NFTs, but is not actually owned by the staking contract, something has gone wrong. this is trivial to validate on-chain and we could add an endpoint to allow any address to show that this invariant has been violated.

question is: is this information useful? what should the contract do in response to this?

one option may be to pause unstaking. that way, votes may still be cast. if the issue is unstaking on behalf of others, governance can recover the contract before NFTs get drained. what else?

**Comment by Art3miX** [comment]
> if a NFT is in the set of staked NFTs, but is not actually owned by the staking contract, something has gone wrong.

What are the cases that this can happen?

The only case I can think of is if its a custom CW721 and the admin was playing with the owner field of the NFTs, in that case, they have bigger problems than voting.

> what should the contract do in response to this?

If I understand it correctly, and the NFT was sent to the staking contract, but for some reason it changed owners without unstaking, then the contract should verify that the NFT is indeed in the set of staked NFTs and the owner is **not** the staking contract, if thats the case we can no longer trust this module to hold the correct staked NFTs data.

If its true, its clear that either theres a bug in the module or something malicious happened, **what the DAO should do in that case?**
I feel like the DAO should be paused because if it happened to 1 NFT it can happen to all of them, and we can't trust votes made by this module any more.

**Extra:** It seems like the module doesn't check if the `token_id` is already staked: https://github.com/DA0-DA0/dao-contracts/blob/main/contracts/voting/dao-voting-cw721-staked/src/state.rs#L61
 and actually allows multiple stakers to stake the same `token_id`.

Of course this doesn't make any sense, because NFT can be only sent be the owner, and after the first sent, the owner is the staking module.
But if we are having the discussion above, it means something needs to be done in that regard in the staking process.
